# Generated by Django 4.1.1 on 2023-02-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('cost', models.IntegerField()),
                ('location', models.CharField(max_length=11)),
            ],
        ),
    ]
